COUNTRY_TO_ISO2: dict[str, str] = {
    "germany": "de",
    "deutschland": "de",
    "austria": "at",
    "oesterreich": "at",
    "switzerland": "ch",
    "schweiz": "ch",
    "netherlands": "nl",
    "niederlande": "nl",
    "belgium": "be",
    "belgien": "be",
    "france": "fr",
    "frankreich": "fr",
    "spain": "es",
    "spanien": "es",
    "italy": "it",
    "italien": "it",
    "poland": "pl",
    "polen": "pl",
    "united states": "us",
    "usa": "us",
    "united kingdom": "gb",
    "uk": "gb",
    "great britain": "gb",
    "canada": "ca",
    "kanada": "ca",
}

COUNTRIES = [
    "Germany",
    "Austria",
    "Switzerland",
    "Netherlands",
    "Belgium",
    "France",
    "Spain",
    "Italy",
    "Poland",
    "United States",
    "United Kingdom",
    "Canada",
]

REGIONS_BY_COUNTRY = {
    "Germany": [
        "Baden-Wuerttemberg",
        "Bayern",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hessen",
        "Mecklenburg-Vorpommern",
        "Niedersachsen",
        "Nordrhein-Westfalen",
        "Rheinland-Pfalz",
        "Saarland",
        "Sachsen",
        "Sachsen-Anhalt",
        "Schleswig-Holstein",
        "Thueringen",
    ]
}
