# Generated by Django 6.0.5 on 2026-05-22 01:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateAttributeDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.PositiveSmallIntegerField(unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "candidate_attribute_definition",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("first_name_norm", models.CharField(db_index=True, max_length=120)),
                ("last_name_norm", models.CharField(db_index=True, max_length=120)),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Weiblich"), ("male", "Maennlich"), ("diverse", "Divers")], max_length=16
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("country", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                (
                    "hair_color",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Schwarz"), (2, "Braun"), (3, "Blond"), (4, "Rot"), (5, "Grau"), (6, "Andere")],
                        default=6,
                    ),
                ),
                ("primary_email", models.EmailField(blank=True, max_length=254)),
                ("secondary_email", models.EmailField(blank=True, max_length=254)),
                ("primary_phone", models.CharField(blank=True, max_length=32)),
                ("secondary_phone", models.CharField(blank=True, max_length=32)),
                ("dating_profile_url", models.URLField(blank=True)),
                (
                    "dating_platform",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Tinder"),
                            (2, "Bumble"),
                            (3, "Hinge"),
                            (4, "OkCupid"),
                            (5, "Match"),
                            (6, "PlentyOfFish"),
                            (7, "Badoo"),
                            (8, "Happn"),
                        ],
                        null=True,
                    ),
                ),
                ("profile_views_count", models.PositiveIntegerField(default=0)),
                ("distinct_recruiter_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate",
            },
        ),
        migrations.CreateModel(
            name="CandidateAttributeVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_anonymous", models.BooleanField(default=False)),
                ("voted_on", models.DateField(default=django.utils.timezone.localdate)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="candidates.candidateattributedefinition",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="candidates.candidate"
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate_attribute_vote",
            },
        ),
        migrations.CreateModel(
            name="CandidateViewLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.GenericIPAddressField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="view_logs", to="candidates.candidate"
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_view_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate_view_log",
            },
        ),
        migrations.CreateModel(
            name="LookupSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("requester_ip", models.GenericIPAddressField()),
                ("initial_country", models.CharField(max_length=120)),
                ("initial_region", models.CharField(max_length=120)),
                ("initial_first_name", models.CharField(max_length=120)),
                ("initial_gender", models.CharField(max_length=16)),
                ("candidate_ids", models.JSONField(default=list)),
                ("case_type", models.CharField(blank=True, max_length=32)),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("step_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("requires_credit", models.BooleanField(default=False)),
                ("step_expires_at", models.DateTimeField()),
                ("profile_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_matches",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lookup_session",
            },
        ),
        migrations.CreateModel(
            name="LookupAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step", models.PositiveSmallIntegerField()),
                ("ip", models.GenericIPAddressField()),
                ("success", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="candidates.lookupsession",
                    ),
                ),
            ],
            options={
                "db_table": "lookup_attempt",
            },
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["country", "region", "city"], name="candidate_country_526514_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["gender", "country", "region"], name="candidate_gender_c887dd_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["first_name_norm", "last_name_norm"], name="candidate_first_n_8fbc2f_idx"),
        ),
        migrations.AddIndex(
            model_name="candidateattributevote",
            index=models.Index(fields=["candidate", "voted_on"], name="candidate_a_candida_7e7b67_idx"),
        ),
        migrations.AddConstraint(
            model_name="candidateattributevote",
            constraint=models.UniqueConstraint(
                fields=("candidate", "recruiter", "attribute"), name="uniq_candidate_recruiter_attribute"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateviewlog",
            index=models.Index(fields=["candidate", "viewed_at"], name="candidate_v_candida_41b4a9_idx"),
        ),
        migrations.AddIndex(
            model_name="candidateviewlog",
            index=models.Index(fields=["ip", "viewed_at"], name="candidate_v_ip_41edee_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupsession",
            index=models.Index(fields=["token"], name="lookup_sess_token_43ac69_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupsession",
            index=models.Index(fields=["status", "updated_at"], name="lookup_sess_status_4e978c_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupattempt",
            index=models.Index(fields=["ip", "created_at"], name="lookup_atte_ip_a2b7cf_idx"),
        ),
    ]
