# Generated by Django 6.0.5 on 2026-05-22 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NodeInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("base_url", models.URLField(unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coordinator", "Coordinator"),
                            ("backup", "Backup Coordinator"),
                            ("replica", "Replica"),
                        ],
                        default="replica",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline"), ("degraded", "Degraded")],
                        default="offline",
                        max_length=16,
                    ),
                ),
                ("api_token_hint", models.CharField(blank=True, max_length=32)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "node_instance",
                "indexes": [
                    models.Index(fields=["role", "status"], name="node_instan_role_680ca2_idx"),
                    models.Index(fields=["heartbeat_at"], name="node_instan_heartbe_5a2f0b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReplicationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(unique=True)),
                ("source_node_id", models.UUIDField()),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "replication_event",
                "indexes": [
                    models.Index(fields=["source_node_id", "acknowledged_at"], name="replication_source__d93467_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ReplicationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("payload_ciphertext", models.TextField()),
                ("payload_checksum", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("acked", "Acked"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_jobs",
                        to="replication.nodeinstance",
                    ),
                ),
            ],
            options={
                "db_table": "replication_job",
                "indexes": [models.Index(fields=["status", "created_at"], name="replication_status_fb0d81_idx")],
            },
        ),
    ]
