# Generated by Django 6.0.5 on 2026-05-22 01:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("search_consumption", "Search Consumption"),
                            ("new_candidate_reward", "New Candidate Reward"),
                            ("existing_vote_reward", "Existing Vote Reward"),
                            ("enrichment_reward", "Enrichment Reward"),
                            ("manual_adjustment", "Manual Adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_ledger_entry",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["recruiter", "created_at"], name="credit_ledg_recruit_1f515c_idx")],
            },
        ),
        migrations.CreateModel(
            name="CreditPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "credits_purchased",
                    models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                ("stripe_payment_intent_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_purchase",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["recruiter", "status"], name="credit_purc_recruit_0fac89_idx")],
            },
        ),
    ]
