# Generated by Django 6.0.5 on 2026-05-22 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiGateToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=512, unique=True)),
                ("ip", models.GenericIPAddressField()),
                ("user_agent_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("rotation_counter", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "security_api_gate_token",
                "indexes": [models.Index(fields=["ip", "expires_at"], name="security_ap_ip_ad281f_idx")],
            },
        ),
        migrations.CreateModel(
            name="CaptchaChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("captcha_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("code_digest", models.CharField(max_length=64)),
                ("salt", models.CharField(max_length=32)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("expires_at", models.DateTimeField()),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "security_captcha_challenge",
                "indexes": [
                    models.Index(fields=["captcha_id"], name="security_ca_captcha_c8bad7_idx"),
                    models.Index(fields=["expires_at"], name="security_ca_expires_3a348b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPBan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.GenericIPAddressField(unique=True)),
                ("reason", models.CharField(max_length=255)),
                ("strike_count", models.PositiveIntegerField(default=0)),
                ("banned_until", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "security_ip_ban",
                "indexes": [models.Index(fields=["banned_until"], name="security_ip_banned__bb00f4_idx")],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("captcha_failed", "Captcha Failed"),
                            ("captcha_solved", "Captcha Solved"),
                            ("api_gate_failed", "API Gate Failed"),
                            ("api_gate_passed", "API Gate Passed"),
                            ("lookup_timeout", "Lookup Timeout"),
                            ("rate_limit", "Rate Limit"),
                            ("ip_banned", "IP Banned"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "security_event",
                "indexes": [
                    models.Index(fields=["event_type", "created_at"], name="security_ev_event_t_f2ceb3_idx"),
                    models.Index(fields=["ip", "created_at"], name="security_ev_ip_2b2220_idx"),
                ],
            },
        ),
    ]
